### ISSUE TITLE
Provide test configuration option

### ISSUE THREAD

**Issue by jambuu** [mozilla-iot/email-sender-adapter#7]
Hi,

This is an awesome feature! It would be great to have a `Test` button to see if the parameters are correct:

![image](https://raw.githubusercontent.com/mozilla-iot/email-sender-adapter/master/doc/email_config.png)

Otherwise, the user does not know what went wrong.
Cheers!

**Comment by mrstegeman** [comment]
This could just be done by using the Email Sender device to send an email.
