### ISSUE TITLE
Send mail instead of notification?

### ISSUE THREAD

**Issue by nickehallgren** [mozilla-iot/email-sender-adapter#8]
Maybe I just do not understand how to use this addon but I've installed it and under things I can send email, notification and simple email and it works perfectly. But I do not really understand how to use it, If I use it in a rule the only option I get is to select property and Action Send notification and I then get a "Notification from WebThings Gateway" without any information about why it was sent. What should I do if I want to send an email or simple email in a rule?

**Comment by hobinjk** [comment]
Sorry for the confusion! I'm updating the documentation today with more information but the gist is that there will be improved support for notifications in our upcoming release on Thursday

**Comment by hobinjk** [comment]
Documentation updated in 67e5b9a, release coming Soon :tm:

**Comment by imhavoc-classic** [comment]
I can create a rule with this add-on, but I cannot configure/customize it. The only thing I can send is "Notification from WebThings Gateway."

**Comment by mrstegeman** [comment]
@imhavoc-classic not sure if you're still using this or not, but you can use the "Email Sender Notification" output block starting with gateway 0.9.

**Comment by cncb-gh** [comment]
This still seems to be an issue in 1.0.  The only option in Rules is to Send Notification and you can't customize the message?
